uploads = []
generated = []

[[outputs]]
id = "gGtX0IqL3JPeibYSqiGcI"
uri = "file://netlify-deploy.zip"
type = "unspecified"
title = "netlify-deploy.zip (v9 — 오프라인 완전 지원)"

[[outputs]]
id = "8-_KvqfTQ0XTRBQ6fL4Am"
uri = "file://netlify-deploy-v2.zip"
type = "unspecified"
title = "V2 배포 패키지 (He's) — 5.2MB"

[[outputs]]
id = "E98OcRrn06OAex5Oi64Ah"
uri = "file://netlify-deploy-v1.zip"
type = "unspecified"
title = "V1 배포 패키지 (EQUUS) — 5.2MB"

[[outputs]]
id = "n6MeJzU5uSIkm0AO9Zqik"
uri = "file://v1_deploy.zip"
type = "unspecified"
title = "V1 (EQUUS) - 묶기 해제 시 공락카 전환 수정"

[[outputs]]
id = "H_aipQURvDCmJhuFS40dH"
uri = "file://v2_deploy.zip"
type = "unspecified"
title = "V2 (He's) - 묶기 해제 시 공락카 전환 수정"
