uploads = []
generated = []

[[outputs]]
id = "gGtX0IqL3JPeibYSqiGcI"
uri = "file://netlify-deploy.zip"
type = "unspecified"
title = "netlify-deploy.zip (v9 — 오프라인 완전 지원)"

[[outputs]]
id = "8-_KvqfTQ0XTRBQ6fL4Am"
uri = "file://netlify-deploy-v2.zip"
type = "unspecified"
title = "netlify-deploy-v2.zip (최신 빌드)"
